"""empty message

Revision ID: ac5aec4f7093
Revises: ece38b5f2bce
Create Date: 2022-12-05 21:39:50.522394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac5aec4f7093'
down_revision = 'ece38b5f2bce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('create_date', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('update_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'update_date')
    op.drop_column('user', 'create_date')
    # ### end Alembic commands ###
