"""empty message

Revision ID: dba3782197ea
Revises: 
Create Date: 2022-11-27 11:48:24.183834

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dba3782197ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('pid', sa.Integer(), nullable=True))
    op.add_column('menu', sa.Column('pname', sa.String(length=20), nullable=True))
    op.add_column('menu', sa.Column('routePath', sa.String(length=100), nullable=True))
    op.add_column('menu', sa.Column('show', sa.String(length=1), nullable=True))
    op.drop_column('menu', 'parent_id')
    op.drop_column('menu', 'flag')
    op.drop_column('menu', 'key_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('key_name', mysql.VARCHAR(length=10), nullable=True))
    op.add_column('menu', sa.Column('flag', mysql.VARCHAR(length=1), nullable=True))
    op.add_column('menu', sa.Column('parent_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('menu', 'show')
    op.drop_column('menu', 'routePath')
    op.drop_column('menu', 'pname')
    op.drop_column('menu', 'pid')
    # ### end Alembic commands ###
