"""empty message

Revision ID: ddb8a208ff64
Revises: dba3782197ea
Create Date: 2022-11-27 11:51:59.022038

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ddb8a208ff64'
down_revision = 'dba3782197ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('state', sa.String(length=1), nullable=True))
    op.drop_column('menu', 'show')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('show', mysql.VARCHAR(length=1), nullable=True))
    op.drop_column('menu', 'state')
    # ### end Alembic commands ###
